#:schema node_modules/wrangler/config-schema.json
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "dendrogram"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-02-06"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[vars]
NODE_VERSION = "22"

[[kv_namespaces]]
binding = "KV"
id = "32e18d98a4934e5f8bef9e00e68c3058"
preview_id = "a9b7245b6c384b23a99fd0d920b067bd"
